namespace DoNotWaste.Models.EnergyStarModels;

[XmlRoot("propertyMetrics")]
public class EnergyStarMetric
{
    [XmlElement("metric")]
    public List<Metric>? Metrics { get; set; }

    [XmlAttribute("year")]
    public int Year { get; set; }

    [XmlAttribute("month")]
    public int Month { get; set; }

    [XmlAttribute("periodType")]
    public PeriodType PeriodType { get; set; }

    [XmlAttribute("propertyId")]
    public long PropertyId { get; set; }


    public DateTime DateYearEnding()
    {
        var firstDayOfNextMonth = new DateTime(Year, Month, 1).AddMonths(1);
        
        var lastDayOfMonth = firstDayOfNextMonth.AddDays(-1);

        return lastDayOfMonth;
    }
}

public class Metric
{
    [XmlElement("value")]
    public string? Value { get; set; }

    [XmlAttribute("name")]
    public string? Name { get; set; }

    [XmlAttribute("id")]
    public long Id { get; set; }

    [XmlAttribute("uom")]
    public string? UnitOfMeasure { get; set; }

    [XmlAttribute("dataType")]
    public DataType DataType { get; set; }

    [XmlAttribute("autoGenerated")]
    public bool AutoGenerated { get; set; }
}

public enum DataType
{
    [XmlEnum("date")]
    Date,
    [XmlEnum("numeric")]
    Numeric,
    [XmlEnum("string")]
    String
}

public enum PeriodType
{
    [XmlEnum("CURRENT")]
    Current,
    [XmlEnum("BASELINE")]
    Baseline
}