using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace DoNotWaste.Models;

using System.Xml.Serialization;

[JsonConverter(typeof(StringEnumConverter))]
public enum UsCanadaStateProvince
{
    [XmlEnum("AK"), JsonProperty("AK")] Alaska,
    [XmlEnum("AL"), JsonProperty("AL")] Alabama,
    [XmlEnum("AR"), JsonProperty("AR")] Arkansas,
    [XmlEnum("AS"), JsonProperty("AS")] AmericanSamoa,
    [XmlEnum("AZ"), JsonProperty("AZ")] Arizona,
    [XmlEnum("CA"), JsonProperty("CA")] California,
    [XmlEnum("CO"), JsonProperty("CO")] Colorado,
    [XmlEnum("CT"), JsonProperty("CT")] Connecticut,
    [XmlEnum("DC"), JsonProperty("DC")] DistrictOfColumbia,
    [XmlEnum("DE"), JsonProperty("DE")] Delaware,
    [XmlEnum("FL"), JsonProperty("FL")] Florida,
    [XmlEnum("GA"), JsonProperty("GA")] Georgia,
    [XmlEnum("GU"), JsonProperty("GU")] Guam,
    [XmlEnum("HI"), JsonProperty("HI")] Hawaii,
    [XmlEnum("IA"), JsonProperty("IA")] Iowa,
    [XmlEnum("ID"), JsonProperty("ID")] Idaho,
    [XmlEnum("IL"), JsonProperty("IL")] Illinois,
    [XmlEnum("IN"), JsonProperty("IN")] Indiana,
    [XmlEnum("KS"), JsonProperty("KS")] Kansas,
    [XmlEnum("KY"), JsonProperty("KY")] Kentucky,
    [XmlEnum("LA"), JsonProperty("LA")] Louisiana,
    [XmlEnum("MA"), JsonProperty("MA")] Massachusetts,
    [XmlEnum("MD"), JsonProperty("MD")] Maryland,
    [XmlEnum("ME"), JsonProperty("ME")] Maine,
    [XmlEnum("MH"), JsonProperty("MH")] MarshallIslands,
    [XmlEnum("MI"), JsonProperty("MI")] Michigan,
    [XmlEnum("MN"), JsonProperty("MN")] Minnesota,
    [XmlEnum("MO"), JsonProperty("MO")] Missouri,
    [XmlEnum("MP"), JsonProperty("MP")] NorthernMarianaIslands,
    [XmlEnum("MS"), JsonProperty("MS")] Mississippi,
    [XmlEnum("MT"), JsonProperty("MT")] Montana,
    [XmlEnum("NC"), JsonProperty("NC")] NorthCarolina,
    [XmlEnum("ND"), JsonProperty("ND")] NorthDakota,
    [XmlEnum("NE"), JsonProperty("NE")] Nebraska,
    [XmlEnum("NH"), JsonProperty("NH")] NewHampshire,
    [XmlEnum("NJ"), JsonProperty("NJ")] NewJersey,
    [XmlEnum("NM"), JsonProperty("NM")] NewMexico,
    [XmlEnum("NN"), JsonProperty("NN")] NavajoNation,
    [XmlEnum("NV"), JsonProperty("NV")] Nevada,
    [XmlEnum("NY"), JsonProperty("NY")] NewYork,
    [XmlEnum("OH"), JsonProperty("OH")] Ohio,
    [XmlEnum("OK"), JsonProperty("OK")] Oklahoma,
    [XmlEnum("OR"), JsonProperty("OR")] Oregon,
    [XmlEnum("PA"), JsonProperty("PA")] Pennsylvania,
    [XmlEnum("PI"), JsonProperty("PI")] PacificIslands,
    [XmlEnum("PR"), JsonProperty("PR")] PuertoRico,
    [XmlEnum("RI"), JsonProperty("RI")] RhodeIsland,
    [XmlEnum("SC"), JsonProperty("SC")] SouthCarolina,
    [XmlEnum("SD"), JsonProperty("SD")] SouthDakota,
    [XmlEnum("TN"), JsonProperty("TN")] Tennessee,
    [XmlEnum("TT"), JsonProperty("TT")] TrustTerritories,
    [XmlEnum("TX"), JsonProperty("TX")] Texas,
    [XmlEnum("UM"), JsonProperty("UM")] UsMinorOutlyingIslands,
    [XmlEnum("UT"), JsonProperty("UT")] Utah,
    [XmlEnum("VA"), JsonProperty("VA")] Virginia,
    [XmlEnum("VI"), JsonProperty("VI")] VirginIslandsOfUs,
    [XmlEnum("VT"), JsonProperty("VT")] Vermont,
    [XmlEnum("WA"), JsonProperty("WA")] Washington,
    [XmlEnum("WI"), JsonProperty("WI")] Wisconsin,
    [XmlEnum("WQ"), JsonProperty("WQ")] WakeIsland,
    [XmlEnum("WV"), JsonProperty("WV")] WestVirginia,
    [XmlEnum("WY"), JsonProperty("WY")] Wyoming,
    [XmlEnum("AB"), JsonProperty("AB")] Alberta,
    [XmlEnum("BC"), JsonProperty("BC")] BritishColumbia,
    [XmlEnum("MB"), JsonProperty("MB")] Manitoba,
    [XmlEnum("NB"), JsonProperty("NB")] NewBrunswick,
    [XmlEnum("NL"), JsonProperty("NL")] NewfoundlandAndLabrador,
    [XmlEnum("NS"), JsonProperty("NS")] NovaScotia,
    [XmlEnum("NT"), JsonProperty("NT")] NorthwestTerritories,
    [XmlEnum("NU"), JsonProperty("NU")] Nunavut,
    [XmlEnum("ON"), JsonProperty("ON")] Ontario,
    [XmlEnum("PE"), JsonProperty("PE")] PrinceEdwardIsland,
    [XmlEnum("QC"), JsonProperty("QC")] Quebec,
    [XmlEnum("SK"), JsonProperty("SK")] Saskatchewan,
    [XmlEnum("YT"), JsonProperty("YT")] Yukon
}
