namespace DoNotWaste.Models.EnergyStarModels.Enums;

public enum EnergyStarPropertyPrimaryFunction
{ 
    [XmlEnum("Adult Education")] AdultEducation,
    [XmlEnum("Ambulatory Surgical Center")] AmbulatorySurgicalCenter,
    [XmlEnum("Aquarium")] Aquarium,
    [XmlEnum("Bank Branch")] BankBranch,
    [XmlEnum("Bar/Nightclub")] BarNightclub,
    [XmlEnum("Barracks")] Barracks,
    [XmlEnum("Bowling Alley")] BowlingAlley,
    [XmlEnum("Casino")] Casino,
    [XmlEnum("College/University")] CollegeUniversity,
    [XmlEnum("Convenience Store with Gas Station")] ConvenienceStoreWithGasStation,
    [XmlEnum("Convenience Store without Gas Station")] ConvenienceStoreWithoutGasStation,
    [XmlEnum("Convention Center")] ConventionCenter,
    [XmlEnum("Courthouse")] Courthouse,
    [XmlEnum("Data Center")] DataCenter,
    [XmlEnum("Distribution Center")] DistributionCenter,
    [XmlEnum("Drinking Water Treatment & Distribution")] DrinkingWaterTreatmentAndDistribution,
    [XmlEnum("Electric Vehicle Charging Station")] ElectricVehicleChargingStation,
    [XmlEnum("Enclosed Mall")] EnclosedMall,
    [XmlEnum("Energy/Power Station")] EnergyPowerStation,
    [XmlEnum("Fast Food Restaurant")] FastFoodRestaurant,
    [XmlEnum("Financial Office")] FinancialOffice,
    [XmlEnum("Fire Station")] FireStation,
    [XmlEnum("Fitness Center/Health Club/Gym")] FitnessCenterHealthClubGym,
    [XmlEnum("Food Sales")] FoodSales,
    [XmlEnum("Food Service")] FoodService,
    [XmlEnum("Hospital (General Medical & Surgical)")] HospitalGeneralMedicalAndSurgical,
    [XmlEnum("Hotel")] Hotel,
    [XmlEnum("Ice/Curling Rink")] IceCurlingRink,
    [XmlEnum("Indoor Arena")] IndoorArena,
    [XmlEnum("K-12 School")] K12School,
    [XmlEnum("Laboratory")] Laboratory,
    [XmlEnum("Library")] Library,
    [XmlEnum("Lifestyle Center")] LifestyleCenter,
    [XmlEnum("Mailing Center/Post Office")] MailingCenterPostOffice,
    [XmlEnum("Manufacturing/Industrial Plant")] ManufacturingIndustrialPlant,
    [XmlEnum("Medical Office")] MedicalOffice,
    [XmlEnum("Mixed Use Property")] MixedUseProperty,
    [XmlEnum("Movie Theater")] MovieTheater,
    [XmlEnum("Multifamily Housing")] MultifamilyHousing,
    [XmlEnum("Museum")] Museum,
    [XmlEnum("Non-Refrigerated Warehouse")] NonRefrigeratedWarehouse,
    [XmlEnum("Office")] Office,
    [XmlEnum("Other - Education")] OtherEducation,
    [XmlEnum("Other - Entertainment/Public Assembly")] OtherEntertainmentPublicAssembly,
    [XmlEnum("Other - Lodging/Residential")] OtherLodgingResidential,
    [XmlEnum("Other - Mall")] OtherMall,
    [XmlEnum("Other - Public Services")] OtherPublicServices,
    [XmlEnum("Other - Recreation")] OtherRecreation,
    [XmlEnum("Other - Restaurant/Bar")] OtherRestaurantBar,
    [XmlEnum("Other - Services")] OtherServices,
    [XmlEnum("Other - Stadium")] OtherStadium,
    [XmlEnum("Other - Technology/Science")] OtherTechnologyScience,
    [XmlEnum("Other - Utility")] OtherUtility,
    [XmlEnum("Other")] Other,
    [XmlEnum("Other/Specialty Hospital")] OtherSpecialtyHospital,
    [XmlEnum("Outpatient Rehabilitation/Physical Therapy")] OutpatientRehabilitationPhysicalTherapy,
    [XmlEnum("Parking")] Parking,
    [XmlEnum("Performing Arts")] PerformingArts,
    [XmlEnum("Personal Services (Health/Beauty, Dry Cleaning, etc)")] PersonalServices,
    [XmlEnum("Police Station")] PoliceStation,
    [XmlEnum("Pre-school/Daycare")] PreschoolDaycare,
    [XmlEnum("Prison/Incarceration")] PrisonIncarceration,
    [XmlEnum("Race Track")] RaceTrack,
    [XmlEnum("Refrigerated Warehouse")] RefrigeratedWarehouse,
    [XmlEnum("Repair Services (Vehicle, Shoe, Locksmith, etc)")] RepairServices,
    [XmlEnum("Residence Hall/Dormitory")] ResidenceHallDormitory,
    [XmlEnum("Residential Care Facility")] ResidentialCareFacility,
    [XmlEnum("Restaurant")] Restaurant,
    [XmlEnum("Retail Store")] RetailStore,
    [XmlEnum("Roller Rink")] RollerRink,
    [XmlEnum("Self-Storage Facility")] SelfStorageFacility,
    [XmlEnum("Senior Living Community")] SeniorLivingCommunity,
    [XmlEnum("Single Family Home")] SingleFamilyHome,
    [XmlEnum("Social/Meeting Hall")] SocialMeetingHall,
    [XmlEnum("Stadium (Closed)")] StadiumClosed,
    [XmlEnum("Stadium (Open)")] StadiumOpen,
    [XmlEnum("Strip Mall")] StripMall,
    [XmlEnum("Supermarket/Grocery Store")] SupermarketGroceryStore,
    [XmlEnum("Swimming Pool")] SwimmingPool,
    [XmlEnum("Transportation Terminal/Station")] TransportationTerminalStation,
    [XmlEnum("Urgent Care/Clinic/Other Outpatient")] UrgentCareClinicOtherOutpatient,
    [XmlEnum("Vehicle Dealership")] VehicleDealership,
    [XmlEnum("Veterinary Office")] VeterinaryOffice,
    [XmlEnum("Vocational School")] VocationalSchool,
    [XmlEnum("Wastewater Treatment Plant")] WastewaterTreatmentPlant,
    [XmlEnum("Wholesale Club/Supercenter")] WholesaleClubSupercenter,
    [XmlEnum("Worship Facility")] WorshipFacility,
    [XmlEnum("Zoo")] Zoo
}