namespace DoNotWaste.Models.EnergyStarModels.Enums;

public enum EnergyStarMeterType
{
    [XmlEnum("Coal Anthracite")] CoalAnthracite,
    [XmlEnum("Coal Bituminous")] CoalBituminous,
    [XmlEnum("Coke")] Coke,
    [XmlEnum("Diesel")] Diesel,
    [XmlEnum("District Chilled Water - Absorption Chiller using Natural Gas")] DistrictChilledWaterAbsorptionChillerUsingNaturalGas,
    [XmlEnum("District Chilled Water - Electric-Driven Chiller")]DistrictChilledWaterElectricDrivenChiller,
    [XmlEnum("District Chilled Water - Engine-Driven Chiller using Natural Gas")] DistrictChilledWaterEngineDrivenChillerUsingNaturalGas,
    [XmlEnum("District Chilled Water - Other")] DistrictChilledWaterOther,
    [XmlEnum("District Hot Water")] DistrictHotWater,
    [XmlEnum("District Steam")] DistrictSteam,
    [XmlEnum("Electric")] Electric,
    [XmlEnum("Electric on Site Solar")] ElectricOnSiteSolar,
    [XmlEnum("Electric on Site Wind")] ElectricOnSiteWind,
    [XmlEnum("Fuel Oil No 1")] FuelOilNo1,
    [XmlEnum("Fuel Oil No 2")] FuelOilNo2,
    [XmlEnum("Fuel Oil No 4")] FuelOilNo4,
    [XmlEnum("Fuel Oil No 5 or 6")] FuelOilNo5Or6,
    [XmlEnum("Kerosene")] Kerosene,
    [XmlEnum("Natural Gas")] NaturalGas,
    [XmlEnum("Other (Energy)")] OtherEnergy,
    [XmlEnum("Propane")] Propane,
    [XmlEnum("Wood")] Wood,
    [XmlEnum("IT Equipment Input Energy (meters on each piece of equipment)")] ITEquipmentInputEnergy,
    [XmlEnum("Power Distribution Unit (PDU) Input Energy")]  PDUInputEnergy,
    [XmlEnum("Power Distribution Unit (PDU) Output Energy")] PDUOutputEnergy,
    [XmlEnum("Uninterruptible Power Supply (UPS) Output Energy")]UPSOutputEnergy,
    [XmlEnum("Municipally Supplied Potable Water - Mixed Indoor/Outdoor")] MunicipallySuppliedPotableWaterMixedIndoorOutdoor,
    [XmlEnum("Municipally Supplied Potable Water - Indoor")]MunicipallySuppliedPotableWaterIndoor,
    [XmlEnum("Municipally Supplied Potable Water - Outdoor")]MunicipallySuppliedPotableWaterOutdoor,
    [XmlEnum("Municipally Supplied Reclaimed Water - Mixed Indoor/Outdoor")] MunicipallySuppliedReclaimedWaterMixedIndoorOutdoor,
    [XmlEnum("Municipally Supplied Reclaimed Water - Indoor")] MunicipallySuppliedReclaimedWaterIndoor,
    [XmlEnum("Municipally Supplied Reclaimed Water - Outdoor")]  MunicipallySuppliedReclaimedWaterOutdoor,
    [XmlEnum("Other - Mixed Indoor/Outdoor (Water)")] OtherMixedIndoorOutdoorWater,
    [XmlEnum("Other - Outdoor")] OtherOutdoor,
    [XmlEnum("Other - Indoor")] OtherIndoor,
    [XmlEnum("Average Influent Flow")] AverageInfluentFlow,
    [XmlEnum("Well Water - Mixed Indoor/Outdoor")]WellWaterMixedIndoorOutdoor,
    [XmlEnum("Well Water - Indoor")] WellWaterIndoor,
    [XmlEnum("Well Water - Outdoor")] WellWaterOutdoor
}